#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 14 23:18:44 2017

@author: zhouying
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 14 21:02:20 2017

@author: zhouying
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun  7 18:56:46 2017

@author: zhouying
"""

#from __future__ import division, print_function, absolute_import

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from sklearn import cross_validation,preprocessing
import vae
#%matplotlib inline

# Import MNIST data
#from tensorflow.examples.tutorials.mnist import input_data
#mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
data=np.loadtxt('./MNIST_data/ionosphere.txt',dtype='float32')

# Parameters
learning_rate = 0.01
training_epochs = 20
batch_size = 10
display_step = 1
examples_to_show = 10
divide_rate = 0.3
keep_rate = 0.5
# Network Parameters
n_hidden_1 = 25 # 1st layer num features
n_hidden_2 = 128 # 2nd layer num features
n_input = 34 # MNIST data input (img shape: 28*28)
scale = 0.1
# tf Graph input (only pictures)
X = tf.placeholder("float", [None, n_input])
keep_prob = tf.placeholder(tf.float32)  
weights = {
    'encoder_h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
#    'encoder_h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
#    'decoder_h1': tf.Variable(tf.random_normal([n_hidden_2, n_hidden_1])),
    'decoder_h1': tf.Variable(tf.random_normal([n_hidden_1, n_input])),
#    'decoder_h2': tf.Variable(tf.random_normal([n_hidden_1, n_input])),
}
biases = {
    'encoder_b1': tf.Variable(tf.random_normal([n_hidden_1])),
#    'encoder_b2': tf.Variable(tf.random_normal([n_hidden_2])),
#    'decoder_b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'decoder_b1': tf.Variable(tf.random_normal([n_input])),
#    'decoder_b2': tf.Variable(tf.random_normal([n_input])),
}


# Building the encoder
def encoder(x):
    # Encoder Hidden layer with sigmoid activation #1
    layer_1 = tf.nn.sigmoid(tf.add(tf.matmul((x+scale*tf.random_normal((n_input,))), weights['encoder_h1']),
                                   biases['encoder_b1']))
    # Decoder Hidden layer with sigmoid activation #2
#    layer_2 = tf.nn.sigmoid(tf.add(tf.matmul(layer_1, weights['encoder_h2']),
#                                   biases['encoder_b2']))
#    return layer_2
    return layer_1


# Building the decoder
def decoder(x):
    # Encoder Hidden layer with sigmoid activation #1
    layer_1 = tf.nn.sigmoid(tf.add(tf.matmul(x, weights['decoder_h1']),
                                   biases['decoder_b1']))
    # Decoder Hidden layer with sigmoid activation #2
#    layer_2 = tf.nn.sigmoid(tf.add(tf.matmul(layer_1, weights['decoder_h2']),
#                                   biases['decoder_b2']))
#    return layer_2
    return layer_1

# Construct model
encoder_op = encoder(X)
decoder_op = decoder(encoder_op)

# Prediction
y_pred = decoder_op
# Targets (Labels) are the input data.
y_true = X

# Define loss and optimizer, minimize the squared error
cost = tf.reduce_mean(tf.pow(y_true - y_pred, 2)) #+ tf.reduce_mean(tf.pow(weights['encoder_h1'],2)) + tf.reduce_mean(tf.pow(weights['decoder_h1'],2))
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)

# Initializing the variables
init = tf.global_variables_initializer()
#x_train,x_test = cross_validation.train_test_split(data,test_size=0.1)
#y_train = x_train[:,8]
#x_train = x_train[:,0:8]
#y_test = x_test[:,8]
#x_train = x_train[:,0:8]


# Launch the graph
#with tf.Session() as sess:
#    sess.run(init)
#    total_batch = int(x_train.num_examples/batch_size)
#    # Training cycle
#    for epoch in range(training_epochs):
#        # Loop over all batches
#        for i in range(total_batch):
#            batch_xs, batch_ys = x_train.next_batch(batch_size)
#            # Run optimization op (backprop) and cost op (to get loss value)
#            _, c = sess.run([optimizer, cost], feed_dict={X: batch_xs})
#        # Display logs per epoch step
#        if epoch % display_step == 0:
#            print("Epoch:", '%04d' % (epoch+1),
#                  "cost=", "{:.9f}".format(c))
#
#    print("Optimization Finished!")

    # Applying encode and decode over test set
#    encode_decode = sess.run(
#        y_pred, feed_dict={X: mnist.test.images[:examples_to_show]})
#    # Compare original images with their reconstructions
#    f, a = plt.subplots(2, 10, figsize=(10, 2))
#    for i in range(examples_to_show):
#        a[0][i].imshow(np.reshape(mnist.test.images[i], (28, 28)))
#        a[1][i].imshow(np.reshape(encode_decode[i], (28, 28)))
#    f.show()
#    plt.draw()
#    plt.waitforbuttonpress()


def reconstruction_error(x):
   encoder_op = tf.nn.sigmoid(tf.add(tf.matmul(x, weights['encoder_h1']),
                                   biases['encoder_b1']))
   decoder_op = tf.nn.sigmoid(tf.add(tf.matmul(encoder_op, weights['decoder_h1']),
                                   biases['decoder_b1']))

# Prediction
    
# Targets (Labels) are the input data.
    
   cost = x-decoder_op
   return cost
my_model_F1 = []
my_model_auc = []
my_F1 = []
my_auc = []
my_model_gene = []
F1 = []
auc = []
model_gene = []
from sklearn.cross_validation import StratifiedKFold
skf = StratifiedKFold(data[:,n_input],n_folds=int(1/divide_rate))
for train_1,test_1 in skf:
    train = data[train_1,:]
    test = data[test_1,:]
    negative = []
    positive = []#np.empty([None,9])
    
    
    # preprocessing ,normalize it into (0,1)
    min_max_scaler = preprocessing.MinMaxScaler()
    train = np.column_stack((min_max_scaler.fit_transform(train[:,0:n_input]),train[:,n_input]))
    test = np.column_stack((min_max_scaler.transform(test[:,0:n_input]),test[:,n_input]))
    # end of preprocessing
    
    #divide into negative data and positive ones
    for i in range(train.shape[0]):
        if train[i,n_input] == 0:
            negative.append(train[i,:])
        else:
            positive.append(train[i,:])
    negative = np.array(negative)
    positive = np.array(positive)
    x_train_negative = negative[:,0:n_input]
    x_train_positive = positive[:,0:n_input]
    #end of divide
    x_train_orginal = x_train_positive
    
#    genetate the x_train_positive to be balance dataset
    y_train_positive = np.ones(x_train_positive.shape[0])
    gene = vae.myvae(x_train_positive,y_train_positive,(x_train_negative.shape[0]-x_train_positive.shape[0]))
    gene = np.reshape(gene,[len(gene),x_train_positive.shape[1]])
    gene = min_max_scaler.transform(gene)
    x_train_positive = np.row_stack((x_train_positive,gene))
    # end of generation
    
    x_train = train[:,0:n_input]
    y_train = train[:,n_input]
    x_test = test[:,0:n_input]
    y_test = test[:,n_input]
    

#    x = tf.placeholder(tf.float32,[None,n_input])#input images
#    W = tf.Variable(tf.zeros([n_input,1]))
#    b = tf.Variable(tf.zeros([1]))
#    y = tf.nn.softmax(tf.matmul(x,W)+b)
#    y_ = tf.placeholder(tf.float32,[None,1])#input labels
#    cross_entropy =tf.reduce_mean(tf.pow(y_ - y, 2))
#    train_step = tf.train.AdamOptimizer(learning_rate).minimize(cross_entropy)
#    tf.initialize_all_variables().run()
#    total_batch = int(train.shape[0]/batch_size)
#    for epoch in range(training_epochs):
#        # Loop over all batches
#            for i in range(total_batch):
#                batch_xs = train[i*batch_size:(i+1)*batch_size,0:n_input]
#                batch_ys = train[i*batch_size:(i+1)*batch_size,:n_input]
#            # Run optimization op (backprop) and cost op (to get loss value)
#                train_step.run({x: batch_xs,y_: batch_ys})
##saver = tf.train.Saver()
#    correct_prediction = tf.equal(tf.arg_max(y,1),tf.arg_max(y_,1))
#    accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))
#    print(accuracy.eval({x: x_test,y_: y_test}))

#ne_po the ne means the recontruction model, po means the true labels
#b_ne_po = []
#b_ne_ne = []
#b_po_po = []
#b_po_ne = []


#the negative reconstruction model
    with tf.Session() as sess1:
        sess1.run(init)
        total_batch = int(x_train_negative.shape[0]/batch_size)
    # Training cycle
        for epoch in range(training_epochs):
        # Loop over all batches
            for i in range(total_batch):
                batch_xs = x_train_negative[i*batch_size:(i+1)*batch_size,:]
            # Run optimization op (backprop) and cost op (to get loss value)
                _, c = sess1.run([optimizer, cost], feed_dict={X: batch_xs,keep_prob: keep_rate})
        # Display logs per epoch step
#        if epoch % display_step == 0:
#            print("Epoch:", '%04d' % (epoch+1),
#                  "cost=", "{:.9f}".format(c))
#    saver.save(sess1, "./model_negative.ckpt")
        b_ne = sess1.run(reconstruction_error(x_test)) 
        tr_ne = sess1.run(reconstruction_error(x_train)) 
    
        print("Sess1 Optimization Finished!")
# the positive reconstruction model 
    with tf.Session() as sess2:
        sess2.run(init)
        total_batch = int(x_train_positive.shape[0]/batch_size)
    # Training cycle
        for epoch in range(training_epochs):
        # Loop over all batches
            for i in range(total_batch):
                batch_xs = x_train_positive[i*batch_size:(i+1)*batch_size,:]
            # Run optimization op (backprop) and cost op (to get loss value)
                _, c = sess2.run([optimizer, cost], feed_dict={X: batch_xs,keep_prob: keep_rate})
        # Display logs per epoch step
#        if epoch % display_step == 0:
#            print("Epoch:", '%04d' % (epoch+1),
#                  "cost=", "{:.9f}".format(c))
#    saver.save(sess2, "./model_positive.ckpt")
        ge_po = sess2.run(reconstruction_error(x_test)) 
        tr_po = sess2.run(reconstruction_error(x_train)) 
        print("Sess2 Optimization Finished!")

#the positive without generation model
    with tf.Session() as sess3:
        sess3.run(init)
        total_batch = int(x_train_orginal.shape[0]/batch_size)
    # Training cycle
        for epoch in range(training_epochs):
        # Loop over all batches
            for i in range(total_batch):
                batch_xs = x_train_orginal[i*batch_size:(i+1)*batch_size,:]
            # Run optimization op (backprop) and cost op (to get loss value)
                _, c = sess3.run([optimizer, cost], feed_dict={X: batch_xs,keep_prob: keep_rate})
        # Display logs per epoch step
#        if epoch % display_step == 0:
#            print("Epoch:", '%04d' % (epoch+1),
#                  "cost=", "{:.9f}".format(c))
#    saver.save(sess1, "./model_negative.ckpt")
        b_po = sess3.run(reconstruction_error(x_test)) 
#        tr_ne = sess1.run(reconstruction_error(x_train)) 
    
        print("Sess3 Optimization Finished!")

#count the recontrustion error and then compare in the two model
    b_ne = (b_ne **2)
    tr_ne = (tr_ne **2)
  
    tr_po = (tr_po **2)
#    
    b_po = (b_po **2) 
    ge_po = (ge_po**2)
    
    
    b_ne_1 = b_ne.sum(axis=1)
    tr_ne_1 = tr_ne.sum(axis=1)
    b_po_1 = b_po.sum(axis=1)
    tr_po_1 = tr_po.sum(axis=1)
    ge_po_1 = ge_po.sum(axis=1)
    
#predict the labels
    y_pre = []
    for i in range(b_ne.shape[0]):
        if b_ne_1[i]< b_po_1[i]:
            y_pre.append(0)
        else:
            y_pre.append(1)
    y_newpre = []
    for i in range(b_ne.shape[0]):
        if b_ne_1[i]< ge_po_1[i]:
            y_newpre.append(0)
        else:
            y_newpre.append(1)
    
    tr_pre = []
    for i in range(tr_ne.shape[0]):
        if tr_ne_1[i]< tr_po_1[i]:
            tr_pre.append(0)
        else:
            tr_pre.append(1)


##################################
#compute F1 score
    from sklearn import metrics
    my_model_F1.append(metrics.f1_score(y_test, y_pre))
    my_model_auc.append(metrics.roc_auc_score(y_test, y_pre))
    my_F1.append(metrics.f1_score(y_train,tr_pre))
    my_auc.append(metrics.roc_auc_score(y_train, tr_pre))
    my_model_gene.append(metrics.f1_score(y_test, y_newpre))
#    my_cc.append(metrics.confusion_matrix(y_test, y_pre))
#    my_model_gmean.append(metrics.gmean_score(y_test, y_pre))
    print('my model F1:',metrics.f1_score(y_test, y_pre))
    print('my model roc:',metrics.roc_auc_score(y_test, y_pre))
    print('my model generation F1:',metrics.f1_score(y_test, y_newpre))
    print('my model generation auc:',metrics.f1_score(y_test, y_newpre))
#    print('my model:',metrics.confusion_matrix(y_test, y_pre))
    
    


####################################
#compute the normal classification's F1 score

    from sklearn.naive_bayes import GaussianNB
    gnb = GaussianNB()
    y_pred = gnb.fit(train[:,0:n_input], train[:,n_input]).predict(x_test)
    F1.append(metrics.f1_score(y_test, y_pred))
    auc.append(metrics.roc_auc_score(y_test, y_pred))
    
#    cc.append(metrics.roc_auc_score(y_test, y_pred))
    print('F1:',metrics.f1_score(y_test, y_pred))
    print('roc:',metrics.roc_auc_score(y_test, y_pred))
    
#    print('GBN:',metrics.confusion_matrix(y_test, y_pred))
    

#predict the generated samples
    gnb = GaussianNB()
    a = np.ones(x_train_positive.shape[0])
    b = np.zeros(x_train_negative.shape[0])
    y_predne = gnb.fit(np.row_stack((x_train_positive,x_train_negative)),np.append(a,b)).predict(x_test)
    model_gene.append(metrics.f1_score(y_test, y_predne))
#    print('generation F1:',metrics.f1_score(y_test, y_predne))
#    print('generation roc:',metrics.roc_auc_score(y_test, y_predne))
#my_model_F1 = np.array(my_model_F1)
#my_model_auc = np.array(my_model_auc)
#F1 = np.array(F1)
#auc = np.array(auc)
   
print('my_model_mean_F1',np.mean(my_model_F1))
print('my_model_mean_auc',np.mean(my_model_auc))
print('my_mean_F1',np.mean(my_F1))
print('my_mean_auc',np.mean(my_auc))
#print('my_mean_cc',np.mean(my_cc))
print('my_mean_generation_F1',np.mean(my_model_gene))
print('GNB_mean_F1',np.mean(F1))
print('GNB_mean_auc',np.mean(auc))
print('GNB_mean_generation_F1',np.mean(model_gene))
#print('mean_cc',np.mean(cc))